# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-19 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_auto_20190219_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='injection',
            name='purchase_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='purchase_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
